import type { NextPage } from 'next'
import Head from 'next/head'
import AboutMe from '../components/AboutMe'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>hi it's xyn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='editor-width left-0 right-0 m-auto'>
        <AboutMe />
        </div>
      
  
      </main>


    </div>
  )
}

export default Home
